# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\python\qt\MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont, QIcon


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1022, 800)
        MainWindow.setToolTip("")
        MainWindow.setWindowIcon(QIcon('./Icons/pig.png'))
        MainWindow.setWindowTitle('群养猪行为识别检测系统')
        # MainWindow.setFixedSize(MainWindow.width(), MainWindow.height())
        MainWindow.setMinimumSize(1022, 781)
        MainWindow.setStyleSheet("font: 75 10pt \"宋体\";\n"
                                 "\n"
                                 "")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.centralWidget.setMouseTracking(True)
        self.OcclusionBox = QtWidgets.QLabel(self.centralWidget)
        self.OcclusionBox.setText("您还未选择图片")
        self.OcclusionBox.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.OcclusionBox.setGeometry(QtCore.QRect(30, 570, 251, 161))
        self.OcclusionBox.setMouseTracking(True)
        self.OcclusionBox.setStyleSheet("background-color: rgb(0, 0, 0, 0);color: rgb(255, 255, 255, 0);")
        # self.OcclusionBox.setStyleSheet("background-color: rgb(	240,255,240, 0);color: rgb(255, 255, 255, 0);")
        self.timeLabel = QtWidgets.QLabel(self.centralWidget)
        self.timeLabel.setGeometry(QtCore.QRect(750, 745, 230, 16))
        self.timeLabel.setMouseTracking(True)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.timeLabel.setFont(font)
        self.timeLabel.setStyleSheet("color: rgb(241, 241, 241, 180);\n"
                                     "background-color: rgb(0, 0, 0, 125);")
        self.timeLabel.setObjectName("timeLabel")
        self.setBtn = QtWidgets.QPushButton(self.centralWidget)
        self.setBtn.setEnabled(True)
        self.setBtn.setGeometry(QtCore.QRect(830, 20, 36, 36))
        self.setBtn.setAutoFillBackground(False)
        self.setBtn.setMouseTracking(True)
        self.setBtn.setStyleSheet("background: transparent;\n"
                                  "border: transparent;")
        self.setBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./Icons/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setBtn.setIcon(icon)
        self.setBtn.setIconSize(QtCore.QSize(35, 35))
        self.setBtn.setCheckable(True)
        self.setBtn.setAutoRepeat(True)
        self.setBtn.setAutoDefault(False)
        self.setBtn.setObjectName("setBtn")
        self.helpBtn = QtWidgets.QPushButton(self.centralWidget)
        self.helpBtn.setGeometry(QtCore.QRect(930, 20, 36, 36))
        self.helpBtn.setAutoFillBackground(False)
        self.helpBtn.setMouseTracking(True)
        self.helpBtn.setStyleSheet("background: transparent;\n"
                                   "border: transparent;")
        self.helpBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./Icons/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpBtn.setIcon(icon1)
        self.helpBtn.setIconSize(QtCore.QSize(35, 35))
        self.helpBtn.setCheckable(True)
        self.helpBtn.setAutoRepeat(True)
        self.helpBtn.setAutoDefault(False)
        self.helpBtn.setObjectName("helpBtn")
        self.musicBtn = QtWidgets.QPushButton(self.centralWidget)
        self.musicBtn.setGeometry(QtCore.QRect(880, 20, 36, 36))
        self.musicBtn.setAutoFillBackground(False)
        self.musicBtn.setMouseTracking(True)
        self.musicBtn.setStyleSheet("background: transparent;\n"
                                    "border: transparent;")
        self.musicBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./Icons/music.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.musicBtn.setIcon(icon2)
        self.musicBtn.setIconSize(QtCore.QSize(35, 35))
        self.musicBtn.setCheckable(True)
        self.musicBtn.setAutoRepeat(True)
        self.musicBtn.setAutoDefault(False)
        self.musicBtn.setObjectName("musicBtn")
        self.balanceBtn = QtWidgets.QPushButton(self.centralWidget)
        self.balanceBtn.setMouseTracking(True)
        self.balanceBtn.setGeometry(QtCore.QRect(420, 670, 100, 50))
        self.balanceBtn.setStyleSheet("QPushButton{\n"
                                      "    height:40px;\n"
                                      "    border:1px solid #4e6096;\n"
                                      "    background-color: rgb(255, 255, 255, 125);\n"
                                      # "    background-color: rgb(155, 255, 189);\n"
                                      "    color:#2a2a2a;\n"
                                      # "    background-color:#61ddff;\n"
                                      "    font-family:\"微软雅黑\";\n"
                                      "    font-size:17px;\n"
                                      "    font-weight:bold;\n"
                                      "    -moz-border-radius:10px;\n"
                                      "}\n")
        self.balanceBtn.setObjectName("balanceBtn")

        self.resetBtn = QtWidgets.QPushButton(self.centralWidget)
        self.resetBtn.setMouseTracking(True)
        self.resetBtn.setGeometry(QtCore.QRect(120, 730, 61, 28))
        self.resetBtn.setStyleSheet("QPushButton{\n"
                                    "    height:40px;\n"
                                    "    border:1px solid #4e6096;\n"
                                    "    background-color: rgb(255, 255, 255, 125);;\n"
                                    "    color:#2a2a2a;\n"
                                    "    font-family:\"微软雅黑\";\n"
                                    "    font-size:17px;\n"
                                    "    -moz-border-radius:10px;\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color:#2e9eff;\n"
                                    "    border:1px solid #1569bd;\n"
                                    "    color:#ecff3d;\n"
                                    "}")
        self.resetBtn.setObjectName("resetBtn")

        self.selectBtn = QtWidgets.QPushButton(self.centralWidget)
        self.selectBtn.setMouseTracking(True)
        self.selectBtn.setGeometry(QtCore.QRect(300, 670, 100, 50))
        self.selectBtn.setStyleSheet("QPushButton{\n"
                                     "    height:40px;\n"
                                     "    border:1px solid #4e6096;\n"
                                     "    background-color: rgb(155, 255, 189);\n"
                                     "    color:#2a2a2a;\n"
                                     # "    background-color:#61ddff;\n"
                                     "    font-family:\"微软雅黑\";\n"
                                     "    font-size:17px;\n"
                                     "    font-weight:bold;\n"
                                     "    -moz-border-radius:10px;\n"
                                     "}\n"
                                     "QPushButton:hover{\n"
                                     "    background-color:#2e9eff;\n"
                                     "    border:1px solid #1569bd;\n"
                                     "    color:#ecff3d;\n"
                                     "}")
        self.selectBtn.setObjectName("selectBtn")
        self.saveBtn = QtWidgets.QPushButton(self.centralWidget)
        self.saveBtn.setMouseTracking(True)
        self.saveBtn.setGeometry(QtCore.QRect(900, 670, 100, 50))
        self.saveBtn.setStyleSheet("QPushButton{\n"
                                   "    height:40px;\n"
                                   "    border:1px solid #4e6096;\n"
                                   "    background-color: rgb(255, 255, 255, 125);\n"
                                   # "    background-color: rgb(155, 255, 189);\n"
                                   "    color:#2a2a2a;\n"
                                   # "    background-color:#61ddff;\n"
                                   "    font-family:\"微软雅黑\";\n"
                                   "    font-size:17px;\n"
                                   "    font-weight:bold;\n"
                                   "    -moz-border-radius:10px;\n"
                                   "}\n")
        self.saveBtn.setObjectName("saveBtn")
        self.effectBtn = QtWidgets.QPushButton(self.centralWidget)
        self.effectBtn.setGeometry(QtCore.QRect(780, 670, 100, 50))
        self.effectBtn.setMouseTracking(True)
        self.effectBtn.setStyleSheet("QPushButton{\n"
                                     "    height:40px;\n"
                                     "    border:1px solid #4e6096;\n"
                                     "    background-color: rgb(255, 255, 255, 125);\n"
                                     # "    background-color: rgb(155, 255, 189);\n"
                                     "    color:#2a2a2a;\n"
                                     # "    background-color:#61ddff;\n"
                                     "    font-family:\"微软雅黑\";\n"
                                     "    font-size:17px;\n"
                                     "    font-weight:bold;\n"
                                     "    -moz-border-radius:10px;\n"
                                     "}\n")
        self.effectBtn.setObjectName("effectBtn")
        self.originBtn = QtWidgets.QPushButton(self.centralWidget)
        self.originBtn.setGeometry(QtCore.QRect(660, 670, 100, 50))
        self.originBtn.setMouseTracking(True)
        self.originBtn.setStyleSheet("QPushButton{\n"
                                     "    height:40px;\n"
                                     "    border:1px solid #4e6096;\n"
                                     "    background-color: rgb(255, 255, 255, 125);\n"
                                     # "    background-color: rgb(155, 255, 189);\n"
                                     "    color:#2a2a2a;\n"
                                     # "    background-color:#61ddff;\n"
                                     "    font-family:\"微软雅黑\";\n"
                                     "    font-size:17px;\n"
                                     "    font-weight:bold;\n"
                                     "    -moz-border-radius:10px;\n"
                                     "}\n")
        self.originBtn.setObjectName("originBtn")
        self.detectBtn = QtWidgets.QPushButton(self.centralWidget)
        self.detectBtn.setGeometry(QtCore.QRect(540, 670, 100, 50))
        self.detectBtn.setMouseTracking(True)
        self.detectBtn.setStyleSheet("QPushButton{\n"
                                     "    height:40px;\n"
                                     "    border:1px solid #4e6096;\n"
                                     "    background-color: rgb(255, 255, 255, 125);\n"
                                     # "    background-color: rgb(155, 255, 189);\n"
                                     "    color:#2a2a2a;\n"
                                     # "    background-color:#61ddff;\n"
                                     "    font-family:\"微软雅黑\";\n"
                                     "    font-size:17px;\n"
                                     "    font-weight:bold;\n"
                                     "    -moz-border-radius:10px;\n"
                                     "}\n")
        self.detectBtn.setObjectName("detectBtn")
        self.brightLabel = QtWidgets.QLabel(self.centralWidget)
        self.brightLabel.setGeometry(QtCore.QRect(40, 600, 50, 16))
        self.brightLabel.setStyleSheet("color: rgb(244, 244, 244);")
        self.brightLabel.setMouseTracking(True)
        self.brightLabel.setObjectName("brightLabel")
        self.saturatLabel = QtWidgets.QLabel(self.centralWidget)
        self.saturatLabel.setGeometry(QtCore.QRect(40, 650, 50, 15))
        self.saturatLabel.setStyleSheet("color: rgb(244, 244, 244);")
        self.saturatLabel.setMouseTracking(True)
        self.saturatLabel.setObjectName("saturatLabel")
        self.contrastLabel = QtWidgets.QLabel(self.centralWidget)
        self.contrastLabel.setGeometry(QtCore.QRect(40, 700, 50, 15))
        self.contrastLabel.setStyleSheet("color: rgb(244, 244, 244);")
        self.contrastLabel.setMouseTracking(True)
        self.contrastLabel.setObjectName("contrastLabel")
        self.brightSlider = QtWidgets.QSlider(self.centralWidget)
        self.brightSlider.setEnabled(True)
        self.brightSlider.setMinimum(10)
        self.brightSlider.setMaximum(90)
        self.brightSlider.setSingleStep(10)
        self.brightSlider.setGeometry(QtCore.QRect(110, 600, 160, 22))
        self.brightSlider.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.brightSlider.setMouseTracking(False)
        self.brightSlider.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.brightSlider.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.brightSlider.setAutoFillBackground(False)
        self.brightSlider.setSliderPosition(50)
        self.brightSlider.setOrientation(QtCore.Qt.Horizontal)
        self.brightSlider.setObjectName("brightSlider")
        self.brightSlider.setMouseTracking(True)
        self.saturatSlider = QtWidgets.QSlider(self.centralWidget)
        self.saturatSlider.setGeometry(QtCore.QRect(110, 650, 160, 22))
        self.saturatSlider.setSliderPosition(50)
        self.saturatSlider.setMinimum(10)
        self.saturatSlider.setMaximum(90)
        self.saturatSlider.setSingleStep(10)
        self.saturatSlider.setOrientation(QtCore.Qt.Horizontal)
        self.saturatSlider.setObjectName("saturatSlider")
        self.saturatSlider.setMouseTracking(True)
        self.contrastSlider = QtWidgets.QSlider(self.centralWidget)
        self.contrastSlider.setGeometry(QtCore.QRect(110, 700, 160, 22))
        self.contrastSlider.setSliderPosition(50)
        self.contrastSlider.setMinimum(10)
        self.contrastSlider.setMaximum(90)
        self.contrastSlider.setSingleStep(10)
        self.contrastSlider.setOrientation(QtCore.Qt.Horizontal)
        self.contrastSlider.setObjectName("contrastSlider")
        self.contrastSlider.setMouseTracking(True)

        self.pic_mask = QtWidgets.QLabel(self.centralWidget)
        self.pic_mask.setGeometry(QtCore.QRect(0, 0, 1021, 781))
        self.pic_mask.setStyleSheet('background-color: rgba(0, 0, 0, 0);')
        self.pic_mask.setScaledContents(True)
        self.pic_mask.setMouseTracking(True)
        self.pic_mask.setObjectName("pic_mask")

        self.backgroundImg = QtWidgets.QLabel(self.centralWidget)
        self.backgroundImg.setGeometry(QtCore.QRect(0, 0, 1021, 781))
        self.backgroundImg.setStyleSheet("color: rgba(255, 255, 255, 240);\n"
        # self.backgroundImg.setStyleSheet("color: rgba(229, 251, 245, 240);\n"
                                         "font: 12pt \"微软雅黑\";\n"
                                         "\n"
                                         "\n"
                                         "\n"
                                         "\n"
                                         "\n"
                                         "\n"
                                         "\n"
                                         "\n"
                                         "")
        self.backgroundImg.setText("")
        self.backgroundImg.setPixmap(QtGui.QPixmap("./Images/pig3.jpg"))
        self.backgroundImg.setScaledContents(True)
        self.backgroundImg.setMouseTracking(True)
        self.backgroundImg.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.backgroundImg.setIndent(1)
        self.backgroundImg.setObjectName("backgroundImg")
        self.backgroundImg.setMouseTracking(True)

        self.backgroundImg2 = QtWidgets.QLabel(self.centralWidget)
        self.backgroundImg2.setGeometry(QtCore.QRect(0, 0, 1021, 781))
        self.backgroundImg2.setStyleSheet("color: rgba(255, 255, 255, 240);\n"
                                          "font: 12pt \"微软雅黑\";\n")
        self.backgroundImg2.setText("")
        self.backgroundImg2.setPixmap(QtGui.QPixmap("./Images/pig3.jpg"))
        self.backgroundImg2.setScaledContents(True)
        self.backgroundImg2.setMouseTracking(True)
        self.backgroundImg2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.backgroundImg2.setIndent(1)
        self.backgroundImg2.setObjectName("backgroundImg")
        self.backgroundImg2.setMouseTracking(True)

        self.imgDisplayLaebl = QtWidgets.QLabel(self.centralWidget)
        self.imgDisplayLaebl.setGeometry(QtCore.QRect(300, 70, 691, 571))
        self.imgDisplayLaebl.setStyleSheet("QLabel{\n"
                                           "    color: rgb(240, 240, 240,0);\n"
                                           "    font: 18pt \"Times New Roman\";\n"
                                           "}\n"
                                           "QLabel:hover{\n"
                                           "    color: rgb(231, 231, 231);\n"
                                           "    background-color: rgb(0, 0, 0, 75);\n"
                                           "}")
        self.imgDisplayLaebl.setLineWidth(2)
        self.imgDisplayLaebl.setAlignment(QtCore.Qt.AlignCenter)
        self.imgDisplayLaebl.setObjectName("imgDisplayLaebl")
        self.imgDisplayLaebl.setMouseTracking(True)

        self.imgDisplayLaebl2 = QtWidgets.QLabel(self.centralWidget)
        self.imgDisplayLaebl2.setGeometry(QtCore.QRect(300, 70, 691, 571))
        self.imgDisplayLaebl2.setStyleSheet("color: rgb(255, 0, 0);\n"
                                            "font: 20pt \"微软雅黑\";\n"
                                            "background-color: rgb(0, 0, 0, 125);")
        self.imgDisplayLaebl2.setText("模型加载中，请等待")
        self.imgDisplayLaebl2.setLineWidth(2)
        self.imgDisplayLaebl2.setAlignment(QtCore.Qt.AlignCenter)
        self.imgDisplayLaebl2.setObjectName("imgDisplayLaebl2")
        self.imgDisplayLaebl2.setVisible(False)

        self.imgInfoLabel = QtWidgets.QLabel(self.centralWidget)
        self.imgInfoLabel.setMouseTracking(True)
        self.imgInfoLabel.setWordWrap(True)
        self.imgInfoLabel.setGeometry(QtCore.QRect(50, 90, 211, 471))
        self.imgInfoLabel.setStyleSheet("QLabel{\n"
                                        "    font: 10pt \"微软雅黑\";\n"
                                        "    color: rgba(255, 255, 255, 0);\n"
                                        "}\n"
                                        "QLabel:hover{\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(0, 0, 0, 0);\n"
                                        "}")
        self.imgInfoLabel.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.imgInfoLabel.setObjectName("imgInfoLabel")
        self.imgInfoLabel.setMouseTracking(True)
        self.poetryText = QtWidgets.QLabel(self.centralWidget)
        self.poetryText.setGeometry(QtCore.QRect(30, 30, 700, 21))
        self.poetryText.setStyleSheet("color: rgba(255, 255, 255, 240);\n"
                                      "font: 12pt \"微软雅黑\";\n"
                                      "")
        self.poetryText.setObjectName("poetryText")
        self.poetryText.setMouseTracking(True)

        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1500, 26))
        self.menuBar.setObjectName("menuBar")
        self.fileMenu = QtWidgets.QMenu('&文件')
        self.fileMenu.setObjectName("fileMenu")
        self.modelMenu = QtWidgets.QMenu('&模型')
        self.modelMenu.setObjectName("modelMenu")
        self.helpMenu = QtWidgets.QMenu('&帮助')
        self.helpMenu.setObjectName("modelMenu")
        MainWindow.setMenuBar(self.menuBar)
        self.menuBar.addMenu(self.fileMenu)
        self.menuBar.addMenu(self.modelMenu)
        self.menuBar.addMenu(self.helpMenu)

        self.actionYolov5s = QtWidgets.QAction(QIcon('./Icons/model/S.png'), "&yolov5s")
        self.actionYolov5s.setCheckable(True)
        self.actionYolov5s.setObjectName("actionYolov5s")
        self.actionYolov5l = QtWidgets.QAction(QIcon('./Icons/model/L.png'), "&yolov5l")
        self.actionYolov5l.setObjectName("actionYolov5l")
        self.actionYolov5m = QtWidgets.QAction(QIcon('./Icons/model/M.png'), "&yolov5m")
        self.actionYolov5m.setObjectName("actionYolov5m")
        self.actionYolov5x = QtWidgets.QAction(QIcon('./Icons/model/X.png'), "&yolov5x")
        self.actionYolov5x.setObjectName("actionYolov5x")

        self.model_list = [self.actionYolov5s, self.actionYolov5m, self.actionYolov5l, self.actionYolov5x]
        for model in self.model_list:
            self.modelMenu.addAction(model)
            self.modelMenu.addSeparator()


        self.actionOpen = QtWidgets.QAction(QIcon('./Icons/open.png'), "&打开")
        self.actionOpen.setObjectName("actionOpen")
        self.actionOpen.setShortcut("Ctrl+F")
        self.actionSave = QtWidgets.QAction(QIcon('./Icons/save.png'), "&保存")
        self.actionSave.setObjectName("actionSave")
        self.actionSave.setShortcut("Ctrl+S")
        self.actionSet = QtWidgets.QAction(QIcon('./Icons/setting3.png'), "&设置")
        self.actionSet.setObjectName("actionSet")
        self.actionQuit = QtWidgets.QAction(QIcon('./Icons/quit.png'), "&退出")
        self.actionQuit.setObjectName("actionQuit")
        self.actionQuit.setShortcut("Ctrl+Q")
        self.actionHelp = QtWidgets.QAction(QIcon('./Icons/help4.png'), "&帮助文档")
        self.actionHelp.setObjectName("actionHelp")

        self.recentMenu = QtWidgets.QMenu('&近期打开')
        self.recentMenu.setObjectName("recentMenu")

        self.fileMenu.addAction(self.actionOpen)
        self.fileMenu.addMenu(self.recentMenu)
        self.fileMenu.addAction(self.actionSave)
        self.fileMenu.addAction(self.actionSet)
        self.fileMenu.addAction(self.actionQuit)

        self.helpMenu.addAction(self.actionHelp)

        menu_list = [self.fileMenu, self.modelMenu, self.helpMenu]
        for menu in menu_list:
            menu.setStyleSheet("color: rgba(0, 0, 0, 255);\n"
                               "font: 10pt \"微软雅黑\";\n"
                               )
        self.menuBar.setStyleSheet("font: 10pt \"微软雅黑\";\n"
                                   "background-color: #e4e4e4;")

        self.logo = QtWidgets.QLabel(self.centralWidget)
        self.logo.setPixmap(QtGui.QPixmap("./Icons/logo.png"))
        self.logo.setGeometry(QtCore.QRect(10, 720, 60, 45))
        self.logo.setScaledContents(True)

        self.backgroundImg2.raise_()
        self.backgroundImg.raise_()
        self.pic_mask.raise_()
        self.timeLabel.raise_()
        self.setBtn.raise_()
        self.helpBtn.raise_()
        self.musicBtn.raise_()
        self.balanceBtn.raise_()
        self.resetBtn.raise_()
        self.selectBtn.raise_()
        self.saveBtn.raise_()
        self.effectBtn.raise_()
        self.originBtn.raise_()
        self.detectBtn.raise_()
        self.OcclusionBox.raise_()
        self.brightLabel.raise_()
        self.saturatLabel.raise_()
        self.contrastLabel.raise_()
        self.brightSlider.raise_()
        self.saturatSlider.raise_()
        self.contrastSlider.raise_()
        self.imgDisplayLaebl.raise_()
        self.imgDisplayLaebl2.raise_()
        self.imgInfoLabel.raise_()
        self.poetryText.raise_()
        self.logo.raise_()

        MainWindow.setCentralWidget(self.centralWidget)
        self.setBtn.setToolTip("设置")
        self.helpBtn.setToolTip("帮助")
        self.musicBtn.setToolTip("音乐")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.timeLabel.setText(_translate("MainWindow", "0000-00-00 00:00:00"))
        self.balanceBtn.setText(_translate("MainWindow", "调整图片"))
        self.resetBtn.setText(_translate("MainWindow", "重置"))
        self.selectBtn.setText(_translate("MainWindow", "选择图片"))
        self.saveBtn.setText(_translate("MainWindow", "保存"))
        self.effectBtn.setText(_translate("MainWindow", "效果图"))
        self.originBtn.setText(_translate("MainWindow", "原图"))
        self.detectBtn.setText(_translate("MainWindow", "检测"))
        self.brightLabel.setText(_translate("MainWindow", "亮度"))
        self.saturatLabel.setText(_translate("MainWindow", "饱和度"))
        self.contrastLabel.setText(_translate("MainWindow", "对比度"))
        self.imgDisplayLaebl.setText(_translate("MainWindow", "please choose a file"))
        self.poetryText.setText(_translate("MainWindow", "不与世俗相论争，耿直乌金是福星"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
