# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'videoUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QComboBox, QFrame


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1037, 762)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 1031, 761))
        self.background.setStyleSheet("background-color: rgb(255, 240, 229);")
        self.background.setText("")
        self.background.setObjectName("background")
        self.imgWin = QtWidgets.QLabel(self.centralwidget)
        self.imgWin.setGeometry(QtCore.QRect(40, 20, 661, 591))
        self.imgWin.setStyleSheet("background-color: rgb(170, 255, 255);\n"
                                  "")
        self.imgWin.setObjectName("widget")
        self.infoLabel = QtWidgets.QLabel(self.centralwidget)
        self.infoLabel.setGeometry(QtCore.QRect(760, 20, 231, 591))
        self.infoLabel.setStyleSheet("QLabel{\n"
                                     "color: rgb(255, 255, 255);\n"
                                     "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, "
                                     "stop:0.447761 rgba(0, 0, 0, 180), stop:0.99005 rgba(255, 0, 0, 0));"
                                     "font: 10pt \"微软雅黑\";"
                                     "color: rgba(255, 255, 255);"
                                     "}")
        self.infoLabel.setAlignment(QtCore.Qt.AlignTop)
        self.infoLabel.setObjectName("infoLabel")
        self.frameLabel = QtWidgets.QLabel(self.centralwidget)
        self.frameLabel.setGeometry(QtCore.QRect(630, 630, 60, 40))
        self.frameLabel.setFrameShape(QFrame.Box)
        self.frameLabel.setStyleSheet("background-color: rgb(189, 255, 213);\n"
                                      "font: 10pt \"微软雅黑\";"
                                      "color: rgba(0, 0, 0);"
                                      "border-color: rgb(0, 0, 0);"
                                      )
        self.frameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.frameLabel.setText("0")
        self.frameLabel.setToolTip("当前帧")
        self.progressSlider = QtWidgets.QSlider(self.centralwidget)
        self.progressSlider.setGeometry(QtCore.QRect(90, 640, 511, 22))
        self.progressSlider.setOrientation(QtCore.Qt.Horizontal)
        self.progressSlider.setObjectName("progressSlider")
        self.progressSlider.setRange(0, 100)
        self.playButton = QtWidgets.QPushButton(self.centralwidget)
        self.playButton.setGeometry(QtCore.QRect(310, 690, 91, 41))
        self.playButton.setStyleSheet("QPushButton{\n"
                                      "    height:40px;\n"
                                      "    border:1px solid #4e6096;\n"
                                      "    background-color: rgb(155, 255, 189);\n"
                                      "    color:#2a2a2a;\n"
                                      "    background-color:#61ddff;\n"
                                      "    font-family:\"微软雅黑\";\n"
                                      "    font-size:17px;\n"
                                      "    font-weight:bold;\n"
                                      "    -moz-border-radius:10px;\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "    background-color:#2e9eff;\n"
                                      "    border:1px solid #1569bd;\n"
                                      "    color:#ecff3d;\n"
                                      "}")
        self.playButton.setObjectName("playButton")
        self.speedButton = QComboBox(self.centralwidget)
        self.speedButton.setGeometry(QtCore.QRect(470, 690, 91, 41))
        self.speedButton.setStyleSheet("font: 10pt \"微软雅黑\";"
                                       "color: rgba(0, 0, 0);"
                                       "QPushButton{\n"
                                       "    height:40px;\n"
                                       "    border:1px solid #4e6096;\n"
                                       "    background-color: rgb(155, 255, 189);\n"
                                       "    color:#2a2a2a;\n"
                                       "    background-color:#61ddff;\n"
                                       "    font-family:\"微软雅黑\";\n"
                                       "    font-size:17px;\n"
                                       "    font-weight:bold;\n"
                                       "    -moz-border-radius:10px;\n"
                                       "}\n"
                                       "QPushButton:hover{\n"
                                       "    background-color:#2e9eff;\n"
                                       "    border:1px solid #1569bd;\n"
                                       "    color:#ecff3d;\n"
                                       "}")
        self.speedButton.setObjectName("speedButton")
        self.speedButton.setToolTip("当前帧率")
        self.replayButton = QtWidgets.QPushButton(self.centralwidget)
        self.replayButton.setGeometry(QtCore.QRect(140, 690, 91, 41))
        self.replayButton.setStyleSheet("QPushButton{\n"
                                        "    height:40px;\n"
                                        "    border:1px solid #4e6096;\n"
                                        "    background-color: rgb(155, 255, 189);\n"
                                        "    color:#2a2a2a;\n"
                                        "    background-color:#61ddff;\n"
                                        "    font-family:\"微软雅黑\";\n"
                                        "    font-size:17px;\n"
                                        "    font-weight:bold;\n"
                                        "    -moz-border-radius:10px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    background-color:#2e9eff;\n"
                                        "    border:1px solid #1569bd;\n"
                                        "    color:#ecff3d;\n"
                                        "}")
        self.replayButton.setObjectName("replayButton")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(830, 690, 91, 41))
        self.saveButton.setStyleSheet("QPushButton{\n"
                                      "    height:40px;\n"
                                      "    border:1px solid #4e6096;\n"
                                      "    background-color: rgb(155, 255, 189);\n"
                                      "    color:#2a2a2a;\n"
                                      "    background-color:#61ddff;\n"
                                      "    font-family:\"微软雅黑\";\n"
                                      "    font-size:17px;\n"
                                      "    font-weight:bold;\n"
                                      "    -moz-border-radius:10px;\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "    background-color:#2e9eff;\n"
                                      "    border:1px solid #1569bd;\n"
                                      "    color:#ecff3d;\n"
                                      "}")
        self.saveButton.setObjectName("saveButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.playButton.setText(_translate("MainWindow", "播放"))
        # self.speedButton.setText(_translate("MainWindow", "1X"))
        self.replayButton.setText(_translate("MainWindow", "重播"))
        self.saveButton.setText(_translate("MainWindow", "保存"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
